function [defs, names, keys] = preset_styles()
% 预设风格定义文件（风格 + GUI显示名称 统一管理）
% ==================
% 每个预设是一个 struct，包含以下字段：
%   figureColor   - 图窗背景色 [R G B]，范围 0~1
%   axesLineWidth - 坐标轴线宽
%   dataLineWidth - 数据线条线宽
%   fontName      - 字体名称
%   fontSize      - 坐标轴字号
%   titleFontSize - 标题字号
%   fontWeight    - 字体粗细 ('normal' / 'bold')
%   fontAngle     - 字体角度 ('normal' / 'italic')
%   grid          - 网格开关 ('on' / 'off')
%   gridMinor     - 次网格开关 ('on' / 'off')
%   box           - 边框开关 ('on' / 'off')
%   tickDir       - 刻度方向 ('in' / 'out')
%   tickLength    - 刻度长度 (归一化单位)
%   colorScheme   - 关联的配色方案名称 (见 color_schemes.m)
%   markerSize    - 标记大小
%   faceAlpha     - 填充透明度
%   figureWidth   - 坐标轴宽
%   figureHeight  - 坐标轴高
%   dataLineStyle - 线性
%   marker        - 标记
% 【如何修改预设风格的 GUI 显示名称】
% → 每个预设上方紧邻的 names.xxx = '...' 即为显示名称，直接修改字符串即可
%
% 【如何新增预设风格】
% 1. 在文件末尾复制一个预设代码块（包含 names.xxx 和 defs.xxx 两部分）
% 2. 修改 key 名（xxx 部分）、显示名称和各参数值
% 3. 排序按定义顺序自动生成，无需手动维护 keys 列表

% ==================== 预设风格定义 ====================

% --- 1. 通用美化：适合大多数场景 ---
names.default = '通用模板';
defs.default = struct(...
    'description', '通用美化，适合大多数场景', ...
    'figureColor', [1 1 1], ...
    'figureUnits', 'centimeters', ...
    'figureWidth', 16, ...
    'figureHeight', 9, ...
    'axesLineWidth', 1.0, ...
    'dataLineWidth', 1.5, ...
    'fontName', 'Times New Roman', ...
    'fontSize', 18, ...
    'titleFontSize', 18, ...
    'fontWeight', 'normal', ...
    'fontAngle', 'normal', ...
    'grid', 'on', ...
    'gridLineStyle', '--', ...
    'gridAlpha', 0.15, ...
    'gridMinor', 'off', ...
    'minorTick', 'on', ...
    'box', 'on', ...
    'tickDir', 'in', ...
    'tickLength', 0.01, ...
    'colorScheme', 'default', ...
    'markerSize', 6, ...
    'faceAlpha', 0.5);

% --- 2. 细线简约 ---
names.academic = '细线简约';
defs.academic = struct(...
    'description', '细线简约风格', ...
    'figureColor', [1 1 1], ...
    'figureUnits', 'centimeters', ...
    'figureWidth', 16, ...
    'figureHeight', 9, ...
    'axesLineWidth', 1.0, ...
    'dataLineWidth', 1.0, ...
    'fontName', 'Times New Roman', ...
    'fontSize', 18, ...
    'titleFontSize', 18, ...
    'fontWeight', 'normal', ...
    'fontAngle', 'normal', ...
    'grid', 'off', ...
    'gridAlpha', 0.15, ...
    'gridMinor', 'off', ...
    'minorTick', 'off', ...
    'box', 'off', ...
    'tickDir', 'in', ...
    'tickLength', 0.01, ...
    'colorScheme', 'default', ...
    'markerSize', 6, ...
    'faceAlpha', 0.5);

% --- 细线全框风格 ---
names.ieee = '细线全框';
defs.ieee = struct(...
    'description', '细线全框优化', ...
    'figureColor', [1 1 1], ...
    'axesLineWidth', 0.7, ...
    'dataLineWidth', 1.0, ...
    'figureWidth', 16, ...
    'figureHeight', 9, ...
    'fontName', 'Times New Roman', ...
    'fontSize', 12, ...
    'titleFontSize', 14, ...
    'fontWeight', 'normal', ...
    'fontAngle', 'normal', ...
    'gridLineStyle', '--', ...
    'grid', 'on', ...
    'gridMinor', 'off', ...
    'box', 'on', ...
    'tickDir', 'in', ...
    'tickLength', 0.006, ...
    'colorScheme', 'default', ...
    'markerSize', 4, ...
    'faceAlpha', 0.15);

% --- 4. 粗线半框 ---
names.minimal = '粗线半框';
defs.minimal = struct(...
    'figureColor', [1 1 1], ...
    'axesLW', 1.0, ...
    'dataLW', 1.2, ...
    'figureWidth', 16, ...
    'figureHeight', 9, ...
    'fontName', 'Helvetica', ...
    'fontSize', 12, ...
    'titleFontSize', 12, ...
    'axesLineWidth', 1.8, ...
    'fontWeight', 'bold', ...
    'grid', 'off', ...
    'box', 'off', ...
    'minorTick', 'on', ...
    'tickDir', 'out', ...
    'colorScheme', 'default');



% ==================== 自动排序（按定义先后顺序）====================
keys = fieldnames(defs);

% ==================== 新增预设示例（取消注释即可使用）====================
% 复制下面代码块到上方 defs.presentation 的 ); 之后，修改 key 名和参数即可
% 排序由 fieldnames(defs) 自动按定义顺序生成，无需手动维护 keys 列表
%
% % --- 8. 自定义风格：请修改名称和参数 ---
% names.my_style = '我的自定义风格';
% defs.my_style = struct(...
%     'figureColor', [1 1 1], ...
%     'axesLineWidth', 1.0, ...
%     'dataLineWidth', 1.5, ...
%     'fontName', 'Arial', ...
%     'fontSize', 10, ...
%     'titleFontSize', 12, ...
%     'fontWeight', 'normal', ...
%     'fontAngle', 'normal', ...
%     'grid', 'on', ...
%     'gridMinor', 'off', ...
%     'box', 'on', ...
%     'tickDir', 'in', ...
%     'tickLength', 0.01, ...
%     'colorScheme', 'default', ...
%     'markerSize', 6, ...
%     'faceAlpha', 0.3);
