function [styles, names, keys] = user_styles()
% 用户自定义样式模板（GUI 自动读取版）
% ====================
% 本文件放在 templates 文件夹中，GUI 会自动读取 styles / names / keys。
%
% 【新增用户模板】
% 1. 在文件末尾复制一个 styles.xxx = struct(...) 代码块；
% 2. 修改 xxx 为新的 key，例如 styles.my_style；
% 3. 在对应的 names.xxx = '...' 中设置 GUI 显示名称；
% 4. 保存本文件后，在 GUI 的样式页点击"刷新列表"。
%
% 【字段说明（与 preset_styles.m 完全一致）】
%   figureColor     - 图窗背景色 [R G B]，范围 0~1
%   figureUnits     - 图窗尺寸单位（如 'centimeters'）
%   figureWidth     - 坐标轴宽（单位由 figureUnits 决定）
%   figureHeight    - 坐标轴高
%   axesLineWidth   - 坐标轴线宽
%   dataLineWidth   - 数据线条线宽
%   dataLineStyle   - 单一线型（如 '--'）
%   dataLineStyles  - 多线型轮换，cell 数组（如 {'--', ':', '-.'} ）
%   fontName        - 字体名称
%   fontSize        - 坐标轴字号
%   titleFontSize   - 标题字号
%   fontWeight      - 字体粗细 ('normal' / 'bold')
%   fontAngle       - 字体角度 ('normal' / 'italic')
%   grid            - 网格开关 ('on' / 'off')
%   gridLineStyle   - 网格线型（如 '--'）
%   gridAlpha       - 网格透明度（0~1）
%   gridMinor       - 次网格开关 ('on' / 'off')
%   minorTick       - 小刻度开关 ('on' / 'off')
%   box             - 边框开关 ('on' / 'off')
%   tickDir         - 刻度方向 ('in' / 'out')
%   tickLength      - 刻度长度（归一化单位）
%   colorScheme     - 关联的配色方案名称（见 color_schemes.m）
%   markerSize      - 标记大小
%   marker          - 单一标记（如 'o'）
%   markers         - 多标记轮换，cell 数组（如 {'o', 's', '^'}）
%   markerFaceColor - 标记填充色，支持 'auto' / 'none' / RGB / 颜色字符
%   faceAlpha       - 填充透明度（0~1）
%
% 【如何修改 GUI 显示名称】
% → 每个模板上方紧邻的 names.xxx = '...' 即为显示名称，直接修改字符串即可
%
% 【callback 说明】
% 可额外写 styles.xxx.callback = @myCallback；
% callback 函数须放在 templates 文件夹中作为独立 .m 文件（不能放在本文件内部）。
% callback 会收到 ctx 结构体，含 ctx.getFigure() / ctx.getAxes(fig) / ctx.toast(msg)。

% ==================== 用户模板定义 ====================

% --- 虚线轮换 ---
names.my_style_1 = 'Line_虚线';
styles.my_style_1 = struct(...
    'dataLineStyles', {{'--', ':', '-.', '--', ':', '-.'}});

% --- 标记轮换 ---
names.my_style_2 = 'Line_标记';
styles.my_style_2 = struct(...
    'markers',         {{'o', 's', '^', 'd', 'v', '>', '<', 'p', 'h', 'x', '+'}}, ...
    'markerSize',      6, ...
    'markerFaceColor', 'auto');

% --- 大论文模板 ---
% callback 函数定义在 templates/dissertation.m 中
names.my_style_3 = 'callback模板';
styles.my_style_3 = struct(...
    'figureColor',   [1 1 1], ...
    'figureUnits',   'centimeters', ...
    'figureWidth',   20, ...
    'figureHeight',  13.34, ...
    'axesLineWidth', 1.5, ...
    'dataLineWidth', 1.5, ...
    'fontName',      'Times New Roman', ...
    'fontWeight',    'normal', ...
    'grid',          'on', ...
    'gridLineStyle', '--', ...
    'gridMinor',     'off', ...
    'minorTick',     'on', ...
    'box',           'on', ...
    'tickDir',       'in', ...
    'tickLength',    0.01, ...
    'callback',      @dissertation);

% ==================== 新增用户模板示例（取消注释即可使用）====================
% names.my_new_style = '我的新模板';
% styles.my_new_style = struct(...
%     'figureColor',   [1 1 1], ...
%     'figureUnits',   'centimeters', ...
%     'figureWidth',   16, ...
%     'figureHeight',  9, ...
%     'axesLineWidth', 1.0, ...
%     'dataLineWidth', 1.5, ...
%     'fontName',      'Times New Roman', ...
%     'fontSize',      12, ...
%     'titleFontSize', 14, ...
%     'fontWeight',    'normal', ...
%     'grid',          'on', ...
%     'box',           'on', ...
%     'tickDir',       'in', ...
%     'tickLength',    0.01, ...
%     'colorScheme',   'default');

% ==================== 自动生成排序 ====================
keys = fieldnames(styles);